export const ADD_PLOTS = 'ADD_PLOTS'
export const REMOVE_PLOT = 'REMOVE_PLOT'
export const CHANGE_PLOT_SETTINGS = 'CHANGE_PLOT_SETTINGS'
export const ADD_TABS = 'ADD_TABS'
export const SET_STRUCTURES = 'SET_STRUCTURES'
export const SET_PLOTABLES = 'SET_PLOTABLES'
export const SET_TAB_PLOTS = 'SET_TAB_PLOTS'
export const SET_SESSION_TABS = 'SET_SESSION_TABS'
//Activate
export const SET_ACTIVE_PLOT = 'SET_ACTIVE_PLOT'
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB'
export const SET_ACTIVE_STRUCTS = 'SET_ACTIVE_STRUCTS'
export const SET_ACTIVE_PLOTABLES = 'SET_ACTIVE_PLOTABLES'
//Deactivate
export const DEACTIVATE_STRUCT = 'DEACTIVATE_STRUCT'
export const DEACTIVATE_PLOTABLE = 'DEACTIVATE_PLOTABLE'
export const SET_SESSION = 'SET_SESSION'
export const CHANGE_SESSION_SETTINGS = 'CHANGE_SESSION_SETTINGS'
export const CLEAR_SESSION = 'CLEAR_SESSION'
export const START_LOADING_PLOT = 'START_LOADING_PLOT'
export const END_LOADING_PLOT = 'END_LOADING_PLOT'
export const SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE'

export const SET_PLOTABLE_PLOTS = 'SET_PLOTABLE_PLOTS'


