language: node_js
env:
  global:
    - RELEASE_NAME=build
node_js:
- 12
script: travis_wait npm run build
before_deploy:
  - >
    if ! [ "$BEFORE_DEPLOY_RUN" ]; then
      export BEFORE_DEPLOY_RUN=1;
      cp -r $RELEASE_NAME safe-$RELEASE_NAME
      rm -rf $RELEASE_NAME/sisl-docs
      tar -czf $RELEASE_NAME-$TRAVIS_TAG.tar.gz $RELEASE_NAME
      zip -r $RELEASE_NAME-$TRAVIS_TAG.zip $RELEASE_NAME
      rm -rf $RELEASE_NAME
      mv safe-$RELEASE_NAME $RELEASE_NAME
    fi
deploy:
- provider: pages
  skip_cleanup: true
  github_token:
    secure: rkYPqxpPgnwo2Gb1gSLVrIK3jDK9mzokEecesXxqDRrVcEwuoiy6rLN9rWjcPLIq60y59IW237OLNDfkQCfqmqUaUKTHUXVBCwWERIjosl7uj75W3YDWfx20jki+oqlu2FmsN+xVu1jqr4pNdr6FG/bm26hcWfQOacPev39Q3b21hykdKNs7LCgw9WV5cPQ+uuQW7oo1kb2ckGcOT6EaCFjHnTG3azaqK4ll8olRH2U+igRfRvXC1CM54bpfI0Js8lKIYQkDjmJtStH+3i1cZnIyUaTCefv8jxI4Ks72eHonDV6aikWzja2+wbLcSYMvIlF1VzErA6j5udjz4UlCF6aez57woat1FVNwmuSqPePQAXczkMLfpVVNk0pPLht27ZIQW7Mtmu+ph++jVixEKiL3+OqC8ALHkYg1iSEP2gkVPU3LqqWDO2IdWfcvaa8mog9T5Wwkw+qRC2GT6bG7f1HlqsxY/zp6YTY2xXt06gHUYMq0Kl2kaLJjMLoOMoDIu4NHGTjJul8EiOsd4X/+dtATBRt1gCfxGUjy1gdvGwY8gMkzafWnicURhSamd24FOu29asDnICLldQbDoOIjYQcjh09JzP1p9BHWc+Ql4XZwFSdZPWL90D+6X36jnFLBJW4JGNjqpjvleyhNPqNFv7iVXHpw45/q1sSEdAF7Zn0=
  local_dir: build
  on:
    branch: master
- provider: firebase
  skip_cleanup: true
  project: sislgui
  token:
    secure: sDUu3msjCWRnx9o7WjiYwS+l5rQ1bGkx9Pt1GNwqnKK26Y+F584+sqruTU4/VSobT/tb3tJ9lf1TH2AbXuwMvyCzOB31i8ZEobIztA3L4QL7ziuHAj4uu3NbAYSf+tp7QYe9sMW+5J3/oo24456SBPfr4C8oVyeldKr3mJDIZDMjOwAbJqmCURBvlmaAlQsmzLSM8g9n3a/8xC0yMpXDDrFLUX5j4oYoocW9HjK+x3S2VCWZ4dYnK4GlqVclZtAKt8WvoD3PV0i4T/0wp4E2xL07SwPBWsH+jRjZJ+qYQG0USBM0TLcrdk0mp2J8TmllREsOUYK9bY9Ji9IQzoi3Psb/R6p4CXhAynKOB4jCOte2K8g823iHGPeaPZhLEpk6LLfoy84Pduiz4YbjRHE6D9FO2LNctdErK7sYOrFUFgp+IHjQrPsAPa4aIWecMJDQud+FEfmP654FNghtqo6g4xbHkQLpuFfzi6fQAMhYI3BYY5O2KTCHEmcA5B7siEZBzC+BSE7RmurALxANl7IeBUix9oVMCW6UQo/HiyP3UOJp6nLxBEh2yf7HlWu/eNdbUfHSSTcSzH3a8HRBW61/dTmtiqDALabxIoNu7CSzNwDs9C1K5FRT9mBmzCOwtcf31CDP0T0yV74TaGTqQfW7WlB2W8qLJX9v5kdy/tWBmC0=
  on:
    branch: master
- provider: releases
  api_key:
    secure: rkYPqxpPgnwo2Gb1gSLVrIK3jDK9mzokEecesXxqDRrVcEwuoiy6rLN9rWjcPLIq60y59IW237OLNDfkQCfqmqUaUKTHUXVBCwWERIjosl7uj75W3YDWfx20jki+oqlu2FmsN+xVu1jqr4pNdr6FG/bm26hcWfQOacPev39Q3b21hykdKNs7LCgw9WV5cPQ+uuQW7oo1kb2ckGcOT6EaCFjHnTG3azaqK4ll8olRH2U+igRfRvXC1CM54bpfI0Js8lKIYQkDjmJtStH+3i1cZnIyUaTCefv8jxI4Ks72eHonDV6aikWzja2+wbLcSYMvIlF1VzErA6j5udjz4UlCF6aez57woat1FVNwmuSqPePQAXczkMLfpVVNk0pPLht27ZIQW7Mtmu+ph++jVixEKiL3+OqC8ALHkYg1iSEP2gkVPU3LqqWDO2IdWfcvaa8mog9T5Wwkw+qRC2GT6bG7f1HlqsxY/zp6YTY2xXt06gHUYMq0Kl2kaLJjMLoOMoDIu4NHGTjJul8EiOsd4X/+dtATBRt1gCfxGUjy1gdvGwY8gMkzafWnicURhSamd24FOu29asDnICLldQbDoOIjYQcjh09JzP1p9BHWc+Ql4XZwFSdZPWL90D+6X36jnFLBJW4JGNjqpjvleyhNPqNFv7iVXHpw45/q1sSEdAF7Zn0=
  file_glob: true
  file: build*.*
  on:
    branch: master
    tags: true
    repo: pfebrer96/sislGUIpublic
  skip_cleanup: true
