language: node_js
node_js:
- 12
script: echo script
deploy:
  provider: firebase
  project: sislgui
  token:
    secure: nMBVELVX47iAuUntO++SkDLGWn7bYw061H4oQOj0nrTuFmMJT+5myE1dbd0Kk+M/nEE7P/HuJzIKUV81JvDyscWNR6Njf7VYxwZhdGfD80TBdYinrKXy23xeezsK1kG5txuOzdkjX44SdvGuFWUl1kZ1aRTTH5qGV6SNDgHkBaprBXCKepf3tjSSEIMyhAeTEvJV+XeBfSOBShuEZR7m3f69+Fvli+yp2veg5d/bgtvZ2tR7Ovyb1NEPH3rqJdFB6YmF0wfviBIirYG2taXdhVvwBVBZPn4Obb9YEVuIzlPAcv/hFezh6kplOq04u/z2f7CSyIRQYg1qCh9hFS82clFaueewhVpXfJ8rQkax23P8PxS0J+1PtxDFo452rX+UldEgi82Dub2fJiPS6t201Hutd7Hq6Jo8e4AUF77/YB17qPb52ZxAUz9pNw4sRI7EC0Xr4N4Ih1t3uCVHLUSje2QOHS2IuKgC+euQPHrW4FH9eNZ3tmnVzyLBulQhQH3UBc/d5XotV501IRm3XmAe1SEpIcIw/RjXQynVUyMY6u5br37cCJzAmB9yu0bnatMMF/5+MXr9b96qq9qjgt4ie8O841fCq3jwE1jacDBTmmaT1dTG7xhnCo90GP/HIpnbA8llmyTPLBsEbmNmyEWVQJEUKzBLfJoGaBixL/m6Cl0=