language: node_js
node_js:
- 12
script: travis_wait npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  project: sislgui
  token:
    secure: sDUu3msjCWRnx9o7WjiYwS+l5rQ1bGkx9Pt1GNwqnKK26Y+F584+sqruTU4/VSobT/tb3tJ9lf1TH2AbXuwMvyCzOB31i8ZEobIztA3L4QL7ziuHAj4uu3NbAYSf+tp7QYe9sMW+5J3/oo24456SBPfr4C8oVyeldKr3mJDIZDMjOwAbJqmCURBvlmaAlQsmzLSM8g9n3a/8xC0yMpXDDrFLUX5j4oYoocW9HjK+x3S2VCWZ4dYnK4GlqVclZtAKt8WvoD3PV0i4T/0wp4E2xL07SwPBWsH+jRjZJ+qYQG0USBM0TLcrdk0mp2J8TmllREsOUYK9bY9Ji9IQzoi3Psb/R6p4CXhAynKOB4jCOte2K8g823iHGPeaPZhLEpk6LLfoy84Pduiz4YbjRHE6D9FO2LNctdErK7sYOrFUFgp+IHjQrPsAPa4aIWecMJDQud+FEfmP654FNghtqo6g4xbHkQLpuFfzi6fQAMhYI3BYY5O2KTCHEmcA5B7siEZBzC+BSE7RmurALxANl7IeBUix9oVMCW6UQo/HiyP3UOJp6nLxBEh2yf7HlWu/eNdbUfHSSTcSzH3a8HRBW61/dTmtiqDALabxIoNu7CSzNwDs9C1K5FRT9mBmzCOwtcf31CDP0T0yV74TaGTqQfW7WlB2W8qLJX9v5kdy/tWBmC0=