language: node_js

node_js:
  - 12

script: echo script

deploy:
  provider: firebase
  project: sislgui
  token:
    secure: "WF/ofeLFVq2d0bddqyEFE+8i2Sprl6xITVPKGiVHAc2xph3GjgQ/BLlJl3SbHSWokjYHsthleaf4oMKpwIvCjWo9lTEha8DPjF/KOVTJ/Xc4uVaHNkrWCXKQlS920j/wnVkH1B54HJsmXBHtKo4H4Ih2MHMRYZ9wQv36gyDrIzgNIAQxgm+0dPP5r2AP9EcHJ0pHOLrce/etxU12KyhvNcsoo9z8hFckNPVEBP6vc4uid56IB/rZY4F2fqJT2gdjr+HPBQiUt4wGnm1TRiQTeDi/Cqp8LDjx8nWuWzVsrBQ4xB4jdcjzoly4JOT7g+A9ZZ02ovdClZhv4uwcwvxBrmtD+/V8Ugcxra1VwBfz5Nh4vdxewOfGKYjTgWmUxEXkZDwGB1OmnPKDTuF1QZZSn1l07DXNM8RhBKI3kVbaKNaH7l/wQoSZV2AqH3y5Q2x1VT1Nm0EanExCSCDN6rI2+pWvNkj2BsUw73RpaUdJGjzkRDWBlDZiaF7IkX5xhI00rMh3lylWeOSo2ahJRK6/H4CetWZjM3isyW23+/JudrB0JCqOmbpmTDs5Bz4mfw2oBiWkzPPORsL6YevOFwNGuWu3dG4EqRqnMDj/tNZFUsRsVpH7S+WgleQVYIb40H58w8H78Xy0cxGjzpW0pNrlIG+JCxlV+aGCUab0OsQQpA4="
