language: node_js
node_js:
- 12
script: echo script
deploy:
  provider: firebase
  project: sislgui
  token:
    secure: B8w0sO2hXhqVb6K3j/xV6zyLKwkx8hC1F8Gp88KXAXk5kNAWKPvAfhEd/XfOTbPDAU4hrtzlQlhE959nkASyYQmMnZ0mFcTcIyB21Lf8roQ5D8/yHEkbfc6Z3UnX5Thj2quB9K0lNa/u0KwSM58RQKlz+O/AUG/mtZXOqTjawrae6SFmhHbItWwOB6ekRFczqYF7PfYP0X8I6KFtaMONOGCwrokoygw6kl/62NQJb/m1QyFqGYzl8TS/6rqfmsanVlkRSuiWjPZNW0XbDqyoRg9ASTUYE0pX1+9aEe5qKuAjaNvjbaWwEtx7bg3O8IWFyu+faE/C9D4YrJtLh1bWklBR+CFzRAgub3hf7CKwYUOrjrkdw0LnkVxiQhKUeDAe1OUHtpkfMqqbft6LVAYpyzeS2x6a55jiNzU/YhOOPzNQO2KJakk1YuYhNjJaNSRad4k2PYELsxJqLUGbJaaBAJWliRC5lbO39xzFx6N1gQgrxWssJLLM4jxzc91iMvFqK3v3XpPpWn/ikS7GUqrajfZpm2FgA4/lFqGrP33jWnMQOX31uAPd4KzopIB1qGbd4ytTy3Q+/RD6+pEWlprU6WahysRE+4E5Ri+WxHb3dhdjAdgb/jqtJmoFsMTRPNcnIOVdnulSf3sZDtuDHbzUa3dVPLeoWFE+ueqdUT0Icu8=
