!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2)
!     It contains Fortran 90 wrappers to fortran functions.


      subroutine f2pyinitio_m(f2pysetupfunc)
      use io_m, only : open_file
      use io_m, only : close_file
      use io_m, only : open_file_read
      use io_m, only : open_file_write
      use io_m, only : rewind_file
      use io_m, only : iostat_reset
      use io_m, only : iostat_update
      use io_m, only : iostat_query
      external f2pysetupfunc
      call f2pysetupfunc(open_file,close_file,open_file_read,open_file_w&
     &rite,rewind_file,iostat_reset,iostat_update,iostat_query)
      end subroutine f2pyinitio_m


