name: Build and deploy GUI

on:
  push:
    branches:
      - master
    # paths:
    #   - 'frontend/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install nodejs
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: "Install node packages"
        run: npm install

      - name: Run tests
        run: npm test -- --coverage
      
      - name: Upload code coverage results
        uses: codecov/codecov-action@v1
      
      # Generate the production build
      - name: "Run the build"
        run: npm run build

      - name: Copy the build to the python package
        run: cp -r build ../sisl_gui/build

      - name: Push the new build
        run: |
          cd ..
          git add sisl_gui/build
          git commit -m ${{ github.event.head_commit.message }}
          git push
        
      # Deploy to github pages
      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@132898
        with:
          GITHUB_TOKEN: ${{ github.token }}
          BRANCH: build
          FOLDER: frontend/build