name: Build and deploy GUI

on:
  push:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install nodejs
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      # Install all the dependencies using the cached packages
      - uses: c-hive/gha-npm-cache@v1

      - name: "Install node packages"
        run: npm install

      - name: Run tests
        run: npm test
      
      - name: Upload code coverage results
        uses: codecov/codecov-action@v1
      
      # Generate the production build
      - name: "Run the build"
        run: npm run build
        
      # Deploy to github pages
      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@132898
        with:
          GITHUB_TOKEN: ${{ github.token }}
          BRANCH: build
          FOLDER: build