name: Publish the package to PyPi

on:
  push:
    tags:
      - '*.*.*'
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Sets up python3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8 

      - name: Install build and test dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install setuptools wheel twine
          pip install pytest

      # Upload to TestPyPI
      - name: Build and Upload to PyPi
        run: |
          python3 setup.py sdist bdist_wheel
          twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}